export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_USERS = 'FETCH_USERS';
export const ADD_POST = 'ADD_POST';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';

export const FETCH_USERS_ALBUMS_REQUEST = 'FETCH_USERS_ALBUMS_REQUEST';
export const FETCH_USERS_ALBUMS_SUCCESS = 'FETCH_USERS_ALBUMS_SUCCESS';

export const FETCH_USERS_TODOS_REQUEST = 'FETCH_USERS_TODOS_REQUEST';
export const FETCH_USERS_TODOS_SUCCESS = 'FETCH_USERS_TODOS_SUCCESS';

export const FETCH_USERS_POSTS_REQUEST = 'FETCH_USERS_POSTS_REQUEST';
export const FETCH_USERS_POSTS_SUCCESS = 'FETCH_USERS_POSTS_SUCCESS';
